"""Update table Post - change field name

Revision ID: 366d242365a2
Revises: 65a7de8197e3
Create Date: 2025-05-23 10:40:30.087729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366d242365a2'
down_revision = '65a7de8197e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(length=5000), nullable=False))
        batch_op.drop_column('body')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.VARCHAR(length=140), nullable=False))
        batch_op.drop_column('content')

    # ### end Alembic commands ###
