"""update table user - add fields

Revision ID: 65a7de8197e3
Revises: 6907aaa61a78
Create Date: 2025-05-22 20:26:06.209379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65a7de8197e3'
down_revision = '6907aaa61a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('about_me', sa.String(length=256), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_fullname'), ['fullname'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_fullname'))
        batch_op.drop_column('about_me')
        batch_op.drop_column('last_seen')
        batch_op.drop_column('fullname')

    # ### end Alembic commands ###
